import asyncio
import logging
from typing import Dict, Any, List, Set

logger = logging.getLogger("dag_engine")

class Node:
    """Represents a single agent execution step (Node) in the DAG."""
    def __init__(self, name: str, dependencies: List[str], system_prompt: str):
        self.name = name
        self.dependencies = dependencies  # Nodes that must complete before this one runs
        self.system_prompt = system_prompt

    async def execute(self, state: Dict[str, Any]) -> Dict[str, Any]:
        """Simulates agent execution based on input state."""
        logger.info(f"Node '{self.name}': starting execution...")
        await asyncio.sleep(2)  # Simulate execution cost / LLM delay
        
        # Simple domain-independent mock generation logic
        output = f"Output generated by {self.name} based on prompts."
        logger.info(f"Node '{self.name}': execution completed successfully.")
        
        return {
            "node": self.name,
            "output": output,
            "status": "success"
        }

class DAGEngine:
    """Manages validation, scheduling, and async execution of Node graphs."""
    def __init__(self, nodes: List[Node]):
        self.nodes = {node.name: node for node in nodes}
        self.adjacency_list: Dict[str, Set[str]] = {node.name: set() for node in nodes}
        self.in_degree: Dict[str, int] = {node.name: 0 for node in nodes}
        self._build_graph()

    def _build_graph(self):
        """Builds adjacency list and calculates in-degrees for topological sort."""
        for node in self.nodes.values():
            for dep in node.dependencies:
                if dep in self.nodes:
                    # Dep must execute before Node, so edge goes from Dep -> Node
                    self.adjacency_list[dep].add(node.name)
                    self.in_degree[node.name] += 1
                else:
                    logger.warning(f"Dependency '{dep}' of Node '{node.name}' does not exist in graph.")

    def has_cycles(self) -> bool:
        """Kahn's algorithm check to verify graph is cycle-free (is a valid DAG)."""
        in_deg = self.in_degree.copy()
        queue = [name for name, deg in in_deg.items() if deg == 0]
        visited_count = 0

        while queue:
            node = queue.pop(0)
            visited_count += 1
            for neighbor in self.adjacency_list[node]:
                in_deg[neighbor] -= 1
                if in_deg[neighbor] == 0:
                    queue.append(neighbor)

        return visited_count != len(self.nodes)

    async def execute_graph(self, initial_state: Dict[str, Any], event_callback=None) -> Dict[str, Any]:
        """
        Executes the nodes in topological order.
        If multiple nodes have 0 dependencies, they run concurrently in parallel.
        """
        if self.has_cycles():
            raise ValueError("Invalid Graph: Directed cycle detected. Execution aborted.")

        state = initial_state.copy()
        state["execution_log"] = []
        
        in_deg = self.in_degree.copy()
        # Initial nodes with no dependencies
        queue = [name for name, deg in in_deg.items() if deg == 0]
        
        active_tasks: Dict[str, asyncio.Task] = {}

        while queue or active_tasks:
            # 1. Start all available nodes that have 0 in-degree and aren't already running
            for node_name in list(queue):
                if node_name not in active_tasks:
                    node = self.nodes[node_name]
                    # Broadcast step status change (observability hook)
                    if event_callback:
                        await event_callback(node_name, "running")
                    
                    # Schedule node execution asynchronously
                    active_tasks[node_name] = asyncio.create_task(node.execute(state))
                    queue.remove(node_name)

            # 2. Wait for at least one running task to complete
            done, _ = await asyncio.wait(
                active_tasks.values(), 
                return_when=asyncio.FIRST_COMPLETED
            )

            # 3. Process completed tasks
            for task in done:
                # Find which node name this completed task belongs to
                completed_node = None
                for name, t in active_tasks.items():
                    if t == task:
                        completed_node = name
                        break

                if completed_node:
                    result = task.result()
                    state["execution_log"].append(result)
                    del active_tasks[completed_node]

                    # Broadcast completion
                    if event_callback:
                        await event_callback(completed_node, "success")

                    # Update in-degrees of neighbors
                    for neighbor in self.adjacency_list[completed_node]:
                        in_deg[neighbor] -= 1
                        if in_deg[neighbor] == 0:
                            queue.append(neighbor)

        # Generate a simulated final output package (e.g. zip file layout)
        state["packaged_artifacts"] = {
            "file_count": len(state["execution_log"]),
            "artifacts": [res["node"] + "_output.txt" for res in state["execution_log"]],
            "download_url": "/api/download/campaign-pack.zip"
        }
        return state

# Self-test demonstration if executed directly
if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    
    # Define a basic 4-node pipeline
    # Planner -> Developer & Tester (Parallel) -> Reviewer
    node_planner = Node("Planner", [], "Plan the layout.")
    node_developer = Node("Developer", ["Planner"], "Write the codebase.")
    node_tester = Node("Tester", ["Planner"], "Create unit tests.")
    node_reviewer = Node("Reviewer", ["Developer", "Tester"], "Verify outputs.")

    engine = DAGEngine([node_planner, node_developer, node_tester, node_reviewer])
    
    async def mock_callback(node: str, status: str):
        print(f"[SSE Broadcast Stream] Node: {node} is {status.upper()}")

    print("Running execution graph...")
    asyncio.run(engine.execute_graph({"task": "Build AI platform"}, mock_callback))
